theme: jekyll-theme-modernist
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Effect of Augmentation on Human Activity Recognition
description: Project for UCLA ECEM202A/CSM213A (Fall 2021)
